//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id_contract { get; set; }
        public string Personal_Account { get; set; }
        public string Equipment { get; set; }
        public string Number_Contract { get; set; }
        public Nullable<System.DateTime> Date_Contract { get; set; }
        public Nullable<int> Type_contract { get; set; }
        public Nullable<System.DateTime> Date_Dis_Contract { get; set; }
        public string Reason_Dis { get; set; }
        public Nullable<int> Сonnected_Services { get; set; }
        public Nullable<int> Lease { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string Id_client { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual Lease Lease1 { get; set; }
        public virtual Services Services { get; set; }
        public virtual Type_Contract Type_Contract1 { get; set; }
    }
}
