//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Contract = new HashSet<Contract>();
            this.ListPhone = new HashSet<ListPhone>();
        }
    
        public string Id_Equipments { get; set; }
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Identifiend_Data { get; set; }
        public Nullable<int> Installation_location { get; set; }
        public string Other { get; set; }
        public string Phone_gateway { get; set; }
        public Nullable<System.DateTime> Date_Installation { get; set; }
        public Nullable<int> Amount_Port { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Identified_Data Identified_Data { get; set; }
        public virtual Installation_locations Installation_locations { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListPhone> ListPhone { get; set; }
    }
}
