//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Id_Event { get; set; }
        public Nullable<int> Id_Role { get; set; }
        public string Event { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
