//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installation_locations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installation_locations()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int Id_installation_location { get; set; }
        public Nullable<int> Address { get; set; }
        public string Сonnection_point { get; set; }
        public string Geographical_coordinates { get; set; }
    
        public virtual Address_Eq Address_Eq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
