//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListPhone
    {
        public int Id_ListPhone { get; set; }
        public string Phone { get; set; }
        public string Id_Equipment { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
