//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_Eq> Address_Eq { get; set; }
        public virtual DbSet<Amount_Ports> Amount_Ports { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Form_Product> Form_Product { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Identified_Data> Identified_Data { get; set; }
        public virtual DbSet<Installation_locations> Installation_locations { get; set; }
        public virtual DbSet<Lease> Lease { get; set; }
        public virtual DbSet<ListPhone> ListPhone { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Product> Type_Product { get; set; }
        public virtual DbSet<Type_Contract> Type_Contract { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
