//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Product
    {
        public int Id_TypeProduct { get; set; }
        public Nullable<int> Id_FormProduct { get; set; }
        public string Name_TypeProduct { get; set; }
    
        public virtual Form_Product Form_Product { get; set; }
    }
}
