//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01Telekom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int Id_Worker { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
        public string Worker_Name { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
